name: 'Trivy Terraform Scanner'
description: 'Scan Terraform files for security issues and misconfigurations using Trivy'
author: 'Álex'

branding:
  icon: 'shield'
  color: 'green'

inputs:
  scan-directory:
    description: 'Directory containing Terraform files to scan'
    required: false
    default: '.'
  severity:
    description: 'Severities to include (CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN)'
    required: false
    default: 'CRITICAL,HIGH'
  exit-code:
    description: 'Exit code when issues are found'
    required: false
    default: '1'
  format:
    description: 'Output format (table, json, sarif)'
    required: false
    default: 'table'
  output-file:
    description: 'File to write results to'
    required: false
    default: ''

outputs:
  scan-result:
    description: 'Result of the scan (success, failed, success-with-issues)'
  issues-found:
    description: 'Whether security issues were found (true/false)'
  results-file:
    description: 'Path to results file if output-file was specified'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/alexgar24/action-docker-demo:main'